### ISSUE TITLE
-o option doesn't work for RNAseq_annotate.py

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/NAL_RNA_seq_annotation_pipeline#43]
I recently tried the -o option for RNAseq_annotate.py. Seems like it's expecting a subdirectory with a date to exist. 

```
python3 /lustre/project/nal_genomics/hsiukang/rnannot_venv/bin/RNAseq_annotate.py -i SRR3883760.tsv  -g GCF_008802855.1_Ppyr1.3_genomic.fna.gz -a Ppyr1.3 -o SRR3883760
new
Traceback (most recent call last):
  File "/lustre/project/nal_genomics/hsiukang/rnannot_venv/bin/RNAseq_annotate.py", line 4, in <module>
    __import__('pkg_resources').run_script('rnannot==0.0.1', 'RNAseq_annotate.py')
  File "/lustre/project/nal_genomics/hsiukang/rnannot_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lustre/project/nal_genomics/hsiukang/rnannot_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/lustre/project/nal_genomics/hsiukang/rnannot_venv/lib/python3.7/site-packages/rnannot-0.0.1-py3.7.egg/EGG-INFO/scripts/RNAseq_annotate.py", line 295, in <module>
    os.mkdir(path.join(args.outdir, args.name))
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/project/nal_genomics/monica.poelchau/rnaseq-phopyr/SRR3883760/2021-02-12-12-05-11'
```

**Comment by mpoelchau** [comment]
Looks like the directory has to exist. I'll update the readme.
